### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by Yorega** [imdaftmike/RetroSwitch#1]
love your project very well documented, question is some parts are left out like what type of speakers did you use and also did you use an actual Nintendo digitize cover along with the rails for the joy con. Would love to see more detail info about the volume button.

**Comment by imdaftmike** [comment]
Thanks, because this was for the hack like heck contest, I just dumped everything on here and didn't have time to go through and do a proper write-up.

I'll be revisiting the project soon though and will be able to include much more detail.
